shelters_project/dog_shelters/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shelter_list, name='shelter_list'),
    path('shelter/<int:pk>', views.shelter_detail, name='shelter_detail'),
    path('dog/<int:pk>', views.DogDetailView.as_view(), name='dog_detail'),
    path('dog/register', views.DogCreateView.as_view(), name='dog_register'),
]

shelters_project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dog_shelters.urls')),
]

shelters_project/dog_shelters/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Shelter(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Dog(models.Model):
    shelter = models.ForeignKey(Shelter, on_delete=models.PROTECT)
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=100)
    intake_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('dog_detail', kwargs={"pk": self.pk})

    def __str__(self):
        return self.name
    

shelters_project/dog_shelters/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse
from . import models
# Create your views here.

def index(request):
    return HttpResponse("Abrigos e cães")

def shelter_list(request):
    shelters = models.Shelter.objects.all()
    context = {'shelters': shelters}
    return render(request, 'shelter_list.html', context)

def shelter_detail(request, pk):
    shelter = get_object_or_404(models.Shelter, pk=pk)
    context = {'shelter': shelter}
    return render(request, 'shelter_detail.html', context)

class DogDetailView(generic.DeleteView):
    model = models.Dog
    template_name = 'dog_detail.html'
    context_object_name = 'dog'

class DogCreateView(generic.CreateView):
    model = models.Dog
    template_name = 'dog_form.html'
    fields = ['shelter', 'name', 'description']

shelters_project/dog_shelters/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Site para adoção de cachorros{% endblock %}</title>
    <link rel="stylesheet" href="">
</head>
<body>
    <article>
        <section>
            <h3>Inscrição para adoção</h3>
        </section>
        {% block content %}
        {% endblock %}
    </article>
</body>
</html>

shelters_project/dog_shelters/templates/dog_detail.html
{% extends 'base.html' %}

{% block title %}
{{ dog.name }}
{% endblock %}

{% block content %}
<h2>{{ dog.name }}</h2>
<div>Sobre {{ dog.name }} - {{ dog.description }}</div>
{% endblock %}

shelters_project/dog_shelters/templates/dog_form.html
{% extends 'base.html' %}

{# TODO: Register crispy_forms_tags #}

{% block title %}
Registrar cachorro no abrigo
{% endblock %}

{% block content %}
<h2>Registrar cachorro no abrigo</h2>
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

shelters_project/dog_shelters/templates/shelter_detail.html
{% extends 'base.html' %}

{% block title %}
Shelter list
{% endblock %}

{% block content %}

<h2>{{ shelter.name }}</h2>
<div>Localizado em {{ shelter.location }}</div>
{% if shelter.dog_set.all %}
    <div>Aqui está a lista dos cachorros disponíveis</div>
    {% for dog in shelter.dog_set.all %}
        <div>
            <a href="{% url 'dog_detail' dog.id %}">{{dog.name}}</a>
        </div>
    {% endfor %}
    </div>
{% else %}
    <div>Esse abrigo não tem cachorros disponíveis</div>
{% endif %}
{% endblock %}

shelters_project/dog_shelters/templates/shelter_list.html
{% extends 'base.html' %}

{% block title %}
Lista de abrigos
{% endblock %}

{% block content %}
<h2>Lista de abrigos</h2>
<div>Aqui está a lista de abrigos registrados</div>
    {% for shelter in shelters %}
        <div>
            <a href="{% url 'shelter_detail' shelter.id %}">
                {{shelter.name}}
            </a>
        </div>
        
    {% endfor %}
    <div>
        <a href="{% url 'dog_register' %}">Registrar um cão disponível</a>
    </div>
</div>
{% endblock %}